version: "3.9"
services:
  frontend:
    build:
      context: .
      target: production
    ports:
      - "80:80" # serve frontend via nginx
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
      target: production
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
